/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.upb.chatupb_v2.view;

import edu.upb.chatupb_v2.controller.ContactController;
import edu.upb.chatupb_v2.controller.Mediador;
import edu.upb.chatupb_v2.controller.MessageController;
import edu.upb.chatupb_v2.model.entities.*;
import edu.upb.chatupb_v2.controller.interfaces.IChatView;
import lombok.Setter;
import net.miginfocom.swing.MigLayout;

import javax.swing.*;
import java.awt.*;
import java.util.Date;
import java.util.List;

/**
 * @author rlaredo
 */
public class ChatUI extends javax.swing.JFrame implements IChatView {

    private DefaultListModel<Contact> contacModel = new DefaultListModel<>();
    @Setter
    private MessageController messageController;
    @Setter
    private ContactController contactController;

    /**
     * Creates new form ChatUI
     */
    public ChatUI() {
        initComponents();
        this.jLContactos.setCellRenderer(new ContactRenderer());
        ChatItemReigh chatItemReigh = new ChatItemReigh("Hola como estas?", "Yo", new Date());
        this.jPanelChat.add(chatItemReigh, "wrap, w 80%");

        ChatItemLeft chatItemLeft = new ChatItemLeft("Hola, bien y vos como vas?", "Tu", new Date());
        this.jPanelChat.add(chatItemLeft, "wrap, w 80%, al right");

        this.jPanelChat.repaint();
        this.jPanelChat.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLContactos = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jtMensaje = new javax.swing.JTextField();
        jBtnEnviar = new javax.swing.JButton();
        jPanelChat = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Contactos"));

        jLContactos.setModel(contacModel);
        jLContactos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jLContactos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLContactosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jLContactos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(64, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Sala de Chat"));

        jBtnEnviar.setText("Enviar");
        jBtnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEnviarActionPerformed(evt);
            }
        });

        jPanelChat.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelChatLayout = new javax.swing.GroupLayout(jPanelChat);
        jPanelChat.setLayout(jPanelChatLayout);
        jPanelChatLayout.setHorizontalGroup(
                jPanelChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelChatLayout.setVerticalGroup(
                jPanelChatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 514, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanelChat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jBtnEnviar)))
                                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jPanelChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jBtnEnviar)
                                        .addComponent(jtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        jPanelChat.setMaximumSize(null);

        jPanelChat.setMinimumSize(new java.awt.Dimension(517, 419));

        // Code of sub-components - not shown here

        // Layout setup code - not shown here

        //jSpChat.setViewportView(jPanelChat);
        jPanelChat.setLayout(new MigLayout("fillx"));
        jPanelChat.setMinimumSize(new Dimension(517, 419));

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEnviarActionPerformed
        // TODO add your handling code here:
        Contact contact = contacModel.get(jLContactos.getSelectedIndex());
        TextMessage message = new TextMessage("0000000000000000000001", jtMensaje.getText().toString());
        Mediador.getInstance().sendMessage(contact.getId(), message);
    }//GEN-LAST:event_jBtnEnviarActionPerformed

    private void jLContactosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLContactosMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jLContactosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnEnviar;
    private javax.swing.JList<Contact> jLContactos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelChat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jtMensaje;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onMessage(AbstractMessage message) {
        if (message instanceof Invitacion invitacion) {
            Contact contact = null;
            if (!contactController.exist(invitacion.getIdUsuario())) {
                int respuesta = JOptionPane.showConfirmDialog(this, "Quieres aceptar", "Invitacion", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (respuesta == JOptionPane.YES_OPTION) {
                    contact = new Contact();
                    contact.setId(invitacion.getIdUsuario());
                    contact.setName(invitacion.getNombre());
                    contact.setIp(invitacion.getIp());
                    contact.setStateConnect(true);
                    contactController.save(contact);

                    contacModel.addElement(contact);
                    jLContactos.setSelectedIndex(contacModel.size() - 1);
                }
            } else {
                contact = contactController.getById(invitacion.getIdUsuario());
                if (contact == null) {
                    return;
                }
                contacModel.elements().asIterator().forEachRemaining(cont -> {
                    if (cont.getId().equals(invitacion.getIdUsuario())) {
                        cont.setStateConnect(true);
                    }
                });

//                Collections.list(contacModel.elements()).stream()
//                        .filter(cont -> cont.getId().equals(invitacion.getIdUsuario()))
//                        .findFirst()
//                        .ifPresent(cont -> cont.setStateConnect(true));
            }
            Mediador.getInstance().sendMessage(invitacion.getIdUsuario(), new Aceptar("0000000000000000000001", "Ricardo Laredo"));
        }
    }

    @Override
    public void onLoadData(List<Contact> contacts) {
        this.contacModel.addAll(contacts);
    }
}
