/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.upb.chatupb_v2.view;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLayeredPane;
import javax.swing.text.SimpleAttributeSet;

/**
 *
 * @author rlaredo
 */
public class ChatItemLeft extends JLayeredPane {

    public ChatItemLeft(String message, String sender, Date date) {
        initComponents();
        this.chatText.setText(message);
        SimpleAttributeSet rightAlign = new SimpleAttributeSet();
        this.chatText.setParagraphAttributes(rightAlign, true);
        this.senderName.setText(sender);
        SimpleDateFormat dateFormat = new SimpleDateFormat("HH:mm");
        this.jLHour.setText(dateFormat.format(date));

    }

    /**
     * Creates new form ChatItemLeft
     */
    public ChatItemLeft() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        senderName = new javax.swing.JLabel();
        jLHour = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatText = new edu.upb.chatupb_v2.view.ChatText();
        chatIcon1 = new edu.upb.chatupb_v2.view.ChatIcon();

        setMaximumSize(null);

        senderName.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        senderName.setText("Ricardo Laredo");

        jLHour.setForeground(new java.awt.Color(153, 153, 153));
        jLHour.setText("20:00");

        jScrollPane1.setViewportView(chatText);

        setLayer(senderName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        setLayer(jLHour, javax.swing.JLayeredPane.DEFAULT_LAYER);
        setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        setLayer(chatIcon1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(senderName, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLHour)
                .addGap(0, 38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chatIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chatIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(senderName)
                            .addComponent(jLHour))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private edu.upb.chatupb_v2.view.ChatIcon chatIcon1;
    private edu.upb.chatupb_v2.view.ChatText chatText;
    private javax.swing.JLabel jLHour;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel senderName;
    // End of variables declaration//GEN-END:variables
}
